spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/project/memo;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    #open-in-view 관례상 OSIV 라고 한다.
    #true일 경우 영속성 컨텍스트가 트랜잭션 범위를 넘어선 레이어까지 살아있다.
    #Api라면 클라이언트에게 응답될 때까지, View라면 View가 렌더링될 때까지 영속성컨텍스트가 살아있다.
    #false일 경우 트랜잭션을 종료할 때 영속성 컨텍스트 또한 닫힌다
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true #JPQL 쿼리 확인용

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace